### ISSUE TITLE
Upzip From Files and Folders

### ISSUE THREAD

**Issue by arsandev** [hayd/deno-zip#13]
How can we create zip from existing files and folders?

**Comment by hayd** [comment]
I guess this should be in the README https://github.com/hayd/deno-zip/blob/2745522c174fb5b16f45b452c4c7a5742f04a188/mod.ts#L32

**Comment by arsandev** [comment]
I don't think this is going well

- My Project
- - myfolder

```ts
zipDir("./myfolder");
// or
zipDir("myfolder");
```

no zip generated.

**Comment by virtuoushub** [comment]
@arsandev please try adding an `await` in front of the call to `zipDir`. For example:

```
// either
const zip = await zipDir('./myfolder');
await zip.writeZip("example.zip");
// or
const zip1 = await zipDir('myfolder');
await zip1.writeZip("example1.zip");
// resulted in zip files containing the contents of "myfolder"
```

**Comment by hayd** [comment]
I think this is stale/missing a reproducible example
