### ISSUE TITLE
JSZip used in deno bundles can't be run

### ISSUE THREAD

**Issue by rracariu** [hayd/deno-zip#21]
Using `deno bundle --unstable --config=./tsconfig.json zip.ts > zip.js` to compile the zip creation example [1]
and then running the bundle with:
`deno run -A --unstable zip.js`

Gets this error:
```
error: Uncaught TypeError: Cannot read property 'default' of undefined
                        this._z = new jszip_3_5_0_1.default();
```

The `tsconfig.json` part is mainly for `importsNotUsedAsValues:preserve`

1 - For the doc sample:
```
import { JSZip } from "https://deno.land/x/jszip/mod.ts";

const zip = new JSZip();
zip.addFile("Hello.txt", "Hello World\n");

const img = zip.folder("images");
img.addFile("smile.gif", "\0", { base64: true });

await zip.writeZip("example.zip");
```

**Comment by hayd** [comment]
I am not sure how to get started on this one. Any ideas why this would be?

(Sorry for the slow response.)

I ran it without the --config and it seemed to work? Is that what you are seeing too? (Is this only occurring on --config?)

**Comment by rracariu** [comment]
Couldn't test anymore as Deno 1.5.2 will not compile this anymore

```
Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.61.0/path/mod.ts (at https://deno.land/std@v0.61.0/path/mod.ts)
error: Import 'https://deno.land/std@v0.61.0/path/mod.ts' failed: 404 Not Found
    at https://deno.land/x/jszip@0.7.0/mod.ts:3:0
```

Was hopping that the new bundling engine will solve this issue - but looks that now this package needs to be updated to use the non `@v` schema.

**Comment by rracariu** [comment]
Looks that the latest `0.8.0` version was not published to `deno.land/x/`. I got around it by directly using the GITHub URL `https://raw.githubusercontent.com/hayd/deno-zip/0.8.0/mod.ts` 

But now I get this with the `Deno 1.5.2` bundler:

```
error: Uncaught SyntaxError: Identifier 'a3' has already been declared
    at <anonymous> (file:///C:/tmp/typescript/zip.js:2218:7)
```

**Comment by hayd** [comment]
Thanks @rracariu happy to take a PR, or I will update soon.

Dang, I wonder what I didn't wrong for the /x upload, i thought I had it working. Thanks for letting me know.

**Comment by hayd** [comment]
This seems to no longer be an issue with deno 1.7.1. I can run:

```ts
import { JSZip } from "https://deno.land/x/jszip@0.9.0/mod.ts";

const zip = new JSZip();
zip.addFile("Hello.txt", "Hello World\n");

const img = zip.folder("images");
img.addFile("smile.gif", "\0", { base64: true });

await zip.writeZip("example.zip")
```

```
$ deno bundle --unstable zip.ts > zip.js
$ deno run -A zip.js
```
without error. 🥳
