### ISSUE TITLE
std versions prefixed with 'v' were deprecated recently

### ISSUE THREAD

**Issue by mguilherme** [hayd/deno-zip#26]
When trying to use the library I receive a deprecation error!

```console
$ deno run --allow-read zip_files.ts

Download https://deno.land/std@v0.61.0/fs/mod.ts
Download https://dev.jspm.io/jszip@3.5.0
Download https://deno.land/x/jszip@0.7.0/types.ts
Download https://deno.land/std@v0.61.0/path/mod.ts
Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.61.0/path/mod.ts (at https://deno.land/std@v0.61.0/path/mod.ts)
error: Import 'https://deno.land/std@v0.61.0/path/mod.ts' failed: 404 Not Found
    at https://deno.land/x/jszip@0.7.0/mod.ts:3:0

```

**Comment by jcc10** [comment]
The interm solution is to use the github raw. The permanent one is to make a new patch tag with the updated deps.

**Comment by hayd** [comment]
Can you retry now?
https://deno.land/x/jszip@0.9.0

**Comment by mguilherme** [comment]
> Can you retry now?
> https://deno.land/x/jszip@0.9.0
> 
> Edit: Thanks for this issue and apologies for the delay in response.

Sorry, I just didn't have the time to test, no need to apologize, you are doing this in your free time 👍
